"""Built-in user profiles for the recommender CLI and evaluation harness."""

PROFILES = {
    "high_energy_pop": {
        "genre": "pop",
        "mood": "happy",
        "target_energy": 0.90,
        "target_valence": 0.85,
        "target_acousticness": 0.08,
        "target_popularity": 82,
        "target_decade": 2020,
        "target_mood_intensity": 0.82,
        "target_key": "major",
        "target_complexity": 0.45,
    },
    "chill_lofi": {
        "genre": "lofi",
        "mood": "chill",
        "target_energy": 0.38,
        "target_valence": 0.58,
        "target_acousticness": 0.80,
        "target_popularity": 45,
        "target_decade": 2020,
        "target_mood_intensity": 0.50,
        "target_key": "minor",
        "target_complexity": 0.28,
    },
    "deep_intense_rock": {
        "genre": "rock",
        "mood": "intense",
        "target_energy": 0.92,
        "target_valence": 0.45,
        "target_acousticness": 0.10,
        "target_popularity": 60,
        "target_decade": 2010,
        "target_mood_intensity": 0.90,
        "target_key": "minor",
        "target_complexity": 0.72,
    },
    "sad_banger": {
        "genre": "metal",
        "mood": "sad",
        "target_energy": 0.92,
        "target_valence": 0.25,
        "target_acousticness": 0.08,
        "target_popularity": 55,
        "target_decade": 2010,
        "target_mood_intensity": 0.95,
        "target_key": "minor",
        "target_complexity": 0.80,
    },
    "ghost_genre": {
        "genre": "bluegrass",
        "mood": "chill",
        "target_energy": 0.35,
        "target_valence": 0.62,
        "target_acousticness": 0.80,
        "target_popularity": 40,
        "target_decade": 2020,
        "target_mood_intensity": 0.42,
        "target_key": "major",
        "target_complexity": 0.25,
    },
    "neutral_listener": {
        "genre": "ambient",
        "mood": "relaxed",
        "target_energy": 0.50,
        "target_valence": 0.65,
        "target_acousticness": 0.50,
        "target_popularity": 50,
        "target_decade": 2020,
        "target_mood_intensity": 0.50,
        "target_key": "",
        "target_complexity": 0.50,
    },
    "pop_happy": {
        "genre": "pop",
        "mood": "happy",
        "target_energy": 0.80,
        "target_valence": 0.84,
        "target_acousticness": 0.18,
        "target_popularity": 80,
        "target_decade": 2020,
        "target_mood_intensity": 0.78,
        "target_key": "major",
        "target_complexity": 0.42,
    },
    "study": {
        "genre": "lofi",
        "mood": "focused",
        "target_energy": 0.40,
        "target_valence": 0.58,
        "target_acousticness": 0.75,
        "target_popularity": 40,
        "target_decade": 2020,
        "target_mood_intensity": 0.58,
        "target_key": "minor",
        "target_complexity": 0.26,
    },
    "workout": {
        "genre": "pop",
        "mood": "intense",
        "target_energy": 0.92,
        "target_valence": 0.77,
        "target_acousticness": 0.05,
        "target_popularity": 85,
        "target_decade": 2020,
        "target_mood_intensity": 0.93,
        "target_key": "major",
        "target_complexity": 0.50,
    },
    "night_drive": {
        "genre": "synthwave",
        "mood": "moody",
        "target_energy": 0.76,
        "target_valence": 0.49,
        "target_acousticness": 0.20,
        "target_popularity": 58,
        "target_decade": 2010,
        "target_mood_intensity": 0.76,
        "target_key": "minor",
        "target_complexity": 0.55,
    },
    "hiphop": {
        "genre": "hip-hop",
        "mood": "confident",
        "target_energy": 0.85,
        "target_valence": 0.72,
        "target_acousticness": 0.06,
        "target_popularity": 80,
        "target_decade": 2020,
        "target_mood_intensity": 0.85,
        "target_key": "minor",
        "target_complexity": 0.60,
    },
}

ACTIVE_PROFILE = "high_energy_pop"
